name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.13'
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Environment information
      run: |
        go version
        go env
    - name: Vet
      run: go vet -v ./...
    - name: Lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status ./...
    - name: staticcheck.io
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get honnef.co/go/tools/cmd/staticcheck
        staticcheck -checks all ./...
    - name: Test
      run: go test -race -count=1 ./...
